### ISSUE TITLE
Cannot connect

### ISSUE THREAD

**Issue by berrySkies** [SmartParksOrg/node-red-contrib-chirpstack#11]
Hi
Thanks for creating this package. I cannot get working due to connection error. I get following messages from debug output in node-red.

"No chirpstack connection set"
"TypeError: Cannot read property 'fullAddress' of null"

I am running node-red in docker container and have no problems accessing the chirp-stack server via POST/GET API from node-red.

I have obviously entered my server and login details in the node configuration. Any tips please?

Thanks.

**Comment by adminfriso** [comment]
this is very strange, somehow it looks like the configuration node is not saved correctly. Can u share a screenshot of your host and port (optionaly foo bar'ed)

**Comment by adminfriso** [comment]
I just revieuwed the code, it looks like the node where you are trying to do a call has no connection set. Therefor the error "No chirpstack connection set". Can you check all chirpstack nodes and verify if all connections are set to your configuration node.

**Comment by berrySkies** [comment]
Thanks for looking into this. Here are screenshots of my connection details. They seem persistent.

![Image 6-1-21 at 5 28 pm](https://user-images.githubusercontent.com/5278164/103736775-01514180-5045-11eb-877c-eb9c25aebdf4.jpg)
![Image 6-1-21 at 5 29 pm](https://user-images.githubusercontent.com/5278164/103736801-0adaa980-5045-11eb-8ed0-1f33864dfd2d.jpg)

**Comment by berrySkies** [comment]
A little more information on the console:

6 Jan 18:37:28 - [error] [chirpstack-connection:2848480d.26c988] TypeError: Channel's second argument (credentials) must be a ChannelCredentials

6 Jan 18:37:28 - [error] [chirpstack-user-management:listUsers] No chirpstack connection set

6 Jan 18:37:28 - [error] [chirpstack-device-management:2fa94562.21dd82] No chirpstack connection set

**Comment by berrySkies** [comment]
I reinstalled the nodes and the problem has resolved. Can now connect successfully. Not sure what the issue was.

**Comment by adminfriso** [comment]
I'm not sure either what happened. Good that you got it working. Have fun with it, and if you have any more issues or suggestions let me know!
